title: SpotX
description: Jetpack Compose onboarding tours SDK
# Use a supported GitHub Pages theme
theme: jekyll-theme-cayman
markdown: kramdown
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Customization
includes_dir: _includes
sass:
  style: compressed

# Navbar links
nav:
  - title: Home
    url: /
  - title: Usage
    url: /usage.html
  - title: API
    url: /api/
  - title: Contact
    url: /contact.html 