title: SpotX
description: Jetpack Compose onboarding tours SDK
# Use a supported GitHub Pages theme
theme: jekyll-theme-cayman
markdown: kramdown
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# GitHub Pages project site base URL
url: https://harry-kuria.github.io
baseurl: /SpotX

# Customization
includes_dir: _includes
sass:
  style: compressed

# Navbar links (used by custom layout)
nav:
  - title: Home
    url: /
  - title: Overview
    url: /overview.html
  - title: Architecture
    url: /architecture.html
  - title: Performance
    url: /performance.html
  - title: Theming
    url: /theming.html
  - title: Usage
    url: /usage.html
  - title: API
    url: /api/
  - title: Contact
    url: /contact.html 